FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y --no-install-recommends \
    git \
    wget \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.tar.gz \
    && tar -xzf cmake-3.22.1-linux-x86_64.tar.gz --strip-components=1 -C /usr/local/ \
    && rm cmake-3.22.1-linux-x86_64.tar.gz

ADD ./ /workspace/
ENTRYPOINT ["bash", "/workspace/scripts/build.sh", "/workspace"]
