FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y --no-install-recommends \
    git \
    wget \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.tar.gz \
    && tar -xzf cmake-3.22.1-linux-x86_64.tar.gz --strip-components=1 -C /usr/local/ \
    && rm cmake-3.22.1-linux-x86_64.tar.gz

RUN groupadd -g 1000 latte && useradd -u 1000 -g 1000 -m -d /home/latte latte -s /bin/bash

USER latte
WORKDIR /home/latte
