FROM nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    libopenblas-dev && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g 1000 latte && useradd -u 1000 -g 1000 -m -d /home/latte latte -s /bin/bash

USER latte
WORKDIR /workspace
