FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y --no-install-recommends \
         libatlas-base-dev \
         libprotobuf-dev \
         protobuf-compiler \
         git \
         cmake \
         libgoogle-glog-dev \
         libgflags-dev \
         libopencv-dev && \
     rm -rf /var/lib/apt/lists/*

WORKDIR /workspace