name: Build Latte

on: [push, pull_request]

jobs:
  ubuntu-22-cpu:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev build-essential cmake

      - name: Build
        id: cmake-build
        run: |
          cmake -S . -B build -DBUILD_CUDA=OFF
          cmake --build build -j $(nproc)

  ubuntu-22-cuda:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev build-essential cmake

      - name: CUDA
        uses: Jimver/cuda-toolkit@v0.2.16
        id: cuda-toolkit
        with:
          cuda: '12.5.0'
          method: 'network'

      - name: Build
        id: cmake-build
        run: |
          cmake -S . -B build -DBUILD_CUDA=ON
          cmake --build build -j $(nproc)

  # build_and_test_gpu:
  #   runs-on: [self-hosted, linux, x64, gpu]
  #   env:
  #     CONTAINER_NAME: "latte-run-id-${{ github.run_id }}"
  #     HTTP_PROXY: "http://192.168.1.186:1080"
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 1

  #   - name: Build the Docker image
  #     run: docker build --build-arg https_proxy=${HTTP_PROXY} --build-arg http_proxy=${HTTP_PROXY} -t latte:ci -f docker/dockerfile .

  #   - name: Start Container
  #     run: docker run -d --rm --gpus=all --env HTTPS_PROXY=${HTTP_PROXY} --env HTTP_PROXY=${HTTP_PROXY} -v $PWD:/workspace --name ${CONTAINER_NAME} latte:ci sleep 1200

  #   - name: Build and Test Latte
  #     run: docker exec ${CONTAINER_NAME} bash /workspace/scripts/build_test.sh /workspace

  #   - name: Stop Container
  #     run: docker stop ${CONTAINER_NAME}
