name: Build Latte

on: [push, pull_request]

jobs:
  ubuntu-22-cpu:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev build-essential cmake

      - name: Build
        id: cmake-build
        run: |
          cmake -S . -B build -DUSE_CUDA=OFF
          cmake --build build -j $(nproc)

  ubuntu-22-cuda:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev build-essential cmake

      - name: CUDA
        uses: Jimver/cuda-toolkit@v0.2.16
        id: cuda-toolkit
        with:
          cuda: '12.5.0'
          method: 'network'

      - name: Build
        id: cmake-build
        run: |
          cmake -S . -B build -DUSE_CUDA=ON
          cmake --build build -j $(nproc)
